version: '3.8'

services:
    testing_site:
        image: gprestes/the-internet
        ports: 
            - 7080:5000
        networks: 
            - grid 
    hub:
        image: selenium/hub:latest
        ports: 
            - 4444:4444
        networks: 
            - grid
    chrome:
        image: selenium/node-chrome:latest
        depends_on: 
            - hub
        environment: 
            - HUB_HOST=hub
        networks: 
            - grid
    firefox:
        image: selenium/node-firefox:latest
        depends_on: 
            - hub
        environment: 
            - HUB_HOST=hub
        networks: 
            - grid
networks: 
    grid:
        ipam: 
            config: 
                - subnet: ${SUBNET}